# Generated by .github/scripts/channels.sh at release time. Do not edit by
# hand: the next release overwrites this file, and every digest below is the
# one release 0.1.5 actually published.
class RunnerManager < Formula
  desc "Local-first autoscaler for ephemeral GitHub Actions self-hosted runners"
  homepage "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI"
  version "0.1.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI/releases/download/v0.1.5/runner-manager-0.1.5-aarch64-apple-darwin.tar.gz"
      sha256 "b1c0ec8503e08c79231d8c659bbcf976b6ef224df9c1f88e62213cd30c1d45c0"
    end
    on_intel do
      url "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI/releases/download/v0.1.5/runner-manager-0.1.5-x86_64-apple-darwin.tar.gz"
      sha256 "a113d7808473a952ecc410cbb3aa68c7fdb3538a805a7c3b47c749422caf19e3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI/releases/download/v0.1.5/runner-manager-0.1.5-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1405a488b42459fdceffadb6651e4674bafe42e83a53d8a008925fb30b5b89f3"
    end
    on_intel do
      url "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI/releases/download/v0.1.5/runner-manager-0.1.5-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2382e24d57512bdcb016a0ca29d9f8d4b420a61a85077359a236748f4a119443"
    end
  end

  def install
    # Each archive holds a single top-level directory, which Homebrew strips
    # when it stages the download, so the binary is at the staging root here.
    bin.install "runner-manager"
  end

  def caveats
    <<~CAVEATS
      Installing the published GitHub App grants Repository -> Administration:
      Read and write. That permission also allows deleting, renaming and
      transferring the repository, and it applies even if you only ever use
      runner-manager as a dashboard. See
      https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI#what-you-are-granting
    CAVEATS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/runner-manager --version")
  end
end
