# Generated by .github/scripts/channels.sh at release time. Do not edit by
# hand: the next release overwrites this file, and every digest below is the
# one release 0.1.15 actually published.
class RunnerManager < Formula
  desc "Local-first autoscaler for ephemeral GitHub Actions self-hosted runners"
  homepage "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI"
  version "0.1.15"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI/releases/download/v0.1.15/runner-manager-0.1.15-aarch64-apple-darwin.tar.gz"
      sha256 "6b9dceb60469b392d9f050d611ba26abac90d2f039550408a7ddac46769b4294"
    end
    on_intel do
      url "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI/releases/download/v0.1.15/runner-manager-0.1.15-x86_64-apple-darwin.tar.gz"
      sha256 "ed0e0bd1855e3fc214daee451215feb365349bccbe7718aaad9d5d16848e5fa2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI/releases/download/v0.1.15/runner-manager-0.1.15-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "33f6e2b65fa2b84216e99ca7baed65091b6a2ab38d79da4242ada29af298efaa"
    end
    on_intel do
      url "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI/releases/download/v0.1.15/runner-manager-0.1.15-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "15c50144b5b52635e5502d9cec04b9ebe2fd13709b2320171c6f7ffbda162cce"
    end
  end

  def install
    # Each archive holds a single top-level directory, which Homebrew strips
    # when it stages the download, so the binary is at the staging root here.
    bin.install "runner-manager"
  end

  def caveats
    <<~CAVEATS
      Installing the published GitHub App grants Repository -> Administration:
      Read and write. That permission also allows deleting, renaming and
      transferring the repository, and it applies even if you only ever use
      runner-manager as a dashboard. See
      https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI#what-you-are-granting
    CAVEATS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/runner-manager --version")
  end
end
