# Generated by .github/scripts/channels.sh at release time. Do not edit by
# hand: the next release overwrites this file, and every digest below is the
# one release 0.2.0 actually published.
class RunnerManager < Formula
  desc "Local-first autoscaler for ephemeral GitHub Actions self-hosted runners"
  homepage "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI/releases/download/v0.2.0/runner-manager-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "245c770cd348f114f5b7780b479361f96c4c9d46a5355f375780490ed33134e4"
    end
    on_intel do
      url "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI/releases/download/v0.2.0/runner-manager-0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "169e30db8f1da134c82f3293c8a59d975ea1962a769042a79ca3cc10d823c819"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI/releases/download/v0.2.0/runner-manager-0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "b46e73fc8c99bdc468826577e8b1c79d9b5f1cadb5e20fbc409028c8f2142c5a"
    end
    on_intel do
      url "https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI/releases/download/v0.2.0/runner-manager-0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "09ff2ad43305cd4e002dcfdb92b0ec5aeb8bb5f402091f2a0d3adc276c02795f"
    end
  end

  def install
    # Each archive holds a single top-level directory, which Homebrew strips
    # when it stages the download, so the binary is at the staging root here.
    bin.install "runner-manager"
  end

  def caveats
    <<~CAVEATS
      Installing the published GitHub App grants Repository -> Administration:
      Read and write. That permission also allows deleting, renaming and
      transferring the repository, and it applies even if you only ever use
      runner-manager as a dashboard. See
      https://github.com/IvanMurzak/GitHub-Runner-Scaler-UI#what-you-are-granting
    CAVEATS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/runner-manager --version")
  end
end
